### ISSUE TITLE
Art Todo List

### ISSUE THREAD

**Issue by adkim147** [OtterSquad/SatanGame#1]
_Prioritized items are bolded_
# Satan
- [x] **Standing**
- [x] **Running Animation**
- [ ] **Punch Animation**
# Enemies
- [ ] **Spikes**
- [ ] **Angels**
- [ ] **Soldier enemy**
# Tiles
- [x] Metal Platforms
- [x] Steel Beams
- [ ] Concrete
- [ ] Stone
- [ ] **Wooden Boards**
# Scenery
- [ ] **Sky Background**
- [ ] Grass
- [ ] Buildings
# General
- [ ] **Explosion Animations**
- [ ] Rockets
# Buttons
- [ ] **Pause Button**
- [ ] **Left Button**
- [ ] **Right Button**
- [ ] **Jump Button**
- [ ] **Attack Button**
# Pause Menu Buttons
- [ ] **Main Menu Button**
- [ ] **Restart Level Button**
- [ ] **Help Button**
- [ ] **Touch Controls Button

**Comment by adkim147** [comment]
idk what else
