### ISSUE TITLE
Master Todo List

### ISSUE THREAD

**Issue by adkim147** [OtterSquad/SatanGame#2]
_Prioritized items are bolded_
# Planning
- [ ] **Decide Final Name**
- [ ] **Decide what the pitchfork does**
# Developing
- [ ] **Make web site**
- [ ] **Make all game art (#1)**
- [ ] **Make main game mechanics (#3)**
- [ ] Make main menu (#4)
- [ ] Write story line in detail (dialogue, setting, etc.)
- [ ] Implement Story
# Publishing
- [ ] Upload to game websites

**Comment by acidpoison** [comment]
ALEx G. suggests the name to be **Satan Fireblast 666** and apparently wasn't joking. :/
