### ISSUE TITLE
Game Mechanics Todo List

### ISSUE THREAD

**Issue by adkim147** [OtterSquad/SatanGame#3]
_Prioritized items are bolded_
# General
- [x] Transitions between layouts
- [x] **Hide touch buttons**
- [ ] Moving Platforms
- [x] **Health & Health HUD**
- [x] **Player death**
- [ ] Autosaving after completing a level
# Pause menu
- [x] Pause game
- [x] **Pause menu**
- [x] **Pause menu keyboard UI**
- [x] **Resume button**
- [x] **Back to main menu button**
- [x] **Activate touchscreen button**
# Satan
- [x] **Running & jumping**
- [x] **Punching**
- [ ] Double jump powerup (wings)
- [ ] Dash powerup (hooves)
- [ ] Charge powerup (horns)
- [ ] Ranged attack powerup (fire)
- [ ] Pitchfork weapon (???)
# Enemies
- [x] **Spikes**
- [ ] **Angels**
- [x] **Soldier enemy**
# Bosses
- [ ] Gabe (Gabe Newell)
- [ ] Raph (Raphiel the artist & the ninja turtle)
- [ ] Mike (Michael Jordan)
- [ ] Uriel
- [ ] GOD

**Comment by acidpoison** [comment]
#### Scrapped Features

Debug
Multiple Lives
Stages in levels (all stages are treated as levels now)

**Comment by acidpoison** [comment]
On the topic of saving and loading games:
https://www.scirra.com/tutorials/526/how-to-make-savegames
